# Generated by Django 6.0 on 2025-12-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_coupon_couponusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
