# Generated by Django 6.0 on 2025-12-29 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_is_active_coupon_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 11, 22, 17, 143698, tzinfo=datetime.timezone.utc)),
        ),
    ]
