# Generated by Django 6.0 on 2025-12-30 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 7, 21, 57, 583729, tzinfo=datetime.timezone.utc)),
        ),
    ]
