# Generated by Django 6.0 on 2025-12-30 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 7, 23, 8, 942986, tzinfo=datetime.timezone.utc)),
        ),
    ]
