# Generated by Django 6.0 on 2025-12-30 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_coupon_discount_type_alter_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 9, 26, 2, 568955, tzinfo=datetime.timezone.utc)),
        ),
    ]
