# Generated by Django 6.0 on 2025-12-30 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 9, 58, 51, 812251, tzinfo=datetime.timezone.utc)),
        ),
    ]
