# Generated by Django 6.0 on 2026-01-04 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 12, 13, 8, 392352, tzinfo=datetime.timezone.utc)),
        ),
    ]
