# Generated by Django 6.0 on 2026-01-05 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 11, 23, 13, 528970, tzinfo=datetime.timezone.utc)),
        ),
    ]
