# Generated by Django 6.0 on 2026-01-09 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 10, 14, 55, 578213, tzinfo=datetime.timezone.utc)),
        ),
    ]
