# Generated by Django 6.0 on 2026-01-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 10, 32, 50, 179015, tzinfo=datetime.timezone.utc)),
        ),
    ]
