# Generated by Django 6.0 on 2026-01-12 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 13, 6, 37, 53, 887715, tzinfo=datetime.timezone.utc)),
        ),
    ]
