# Generated by Django 6.0 on 2026-01-15 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 5, 37, 34, 345799, tzinfo=datetime.timezone.utc)),
        ),
    ]
