# Generated by Django 6.0 on 2026-01-19 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 9, 56, 35, 729031, tzinfo=datetime.timezone.utc)),
        ),
    ]
