# Generated by Django 6.0 on 2026-01-19 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0028_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 10, 8, 59, 633334, tzinfo=datetime.timezone.utc)),
        ),
    ]
