# Generated by Django 6.0 on 2026-01-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_created_at_remove_cart_updated_at_and_more'),
        ('catalog', '0013_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variant_type', models.CharField(max_length=50)),
                ('variant_value', models.CharField(max_length=50)),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(choices=[('IN_STOCK', 'In Stock'), ('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
