# Generated by Django 6.0 on 2025-12-30 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productmedia_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
    ]
