# Generated by Django 6.0 on 2025-12-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_productreview_unique_together_and_more'),
        ('users', '0004_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user', 'review_date')},
        ),
    ]
