# Generated by Django 6.0 on 2026-01-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_price_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
