# Generated by Django 6.0 on 2026-01-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_productvariant'),
        ('catalog', '0013_remove_productvariant_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.productvariant'),
        ),
    ]
