# Generated by Django 6.0 on 2025-12-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatus_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='zip_code',
            new_name='pincode',
        ),
    ]
