# Generated by Django 6.0 on 2025-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_zip_code_shipping_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
