# Generated by Django 6.0 on 2025-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usershippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usershippingaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usershippingaddress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddress',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usershippingaddress',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usershippingaddress',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usershippingaddress',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
